name: bacpage
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python >=3.9
  - bc = 1.07.1
  - bcftools = 1.17
  - bedtools = 2.25.0
  - biopython
  - bwa = 0.7.17
  - emboss = 6.6.0
  - fastqc
  - iqtree=2.2.3
  - multiqc
  - pandas
  - qualimap
  - samtools = 1.17
  - snakemake-minimal = 7.31.0
  - snp-sites
  - fastp
  - lighter
  - flash
  - unicycler
  - prokka
  - quast
  - abricate
  - gubbins
  - pytest
  - kmc
