channels:
  - conda-forge
  - bioconda
dependencies:
  - python <3.12,>=3.9
  - bc
  - bcftools = 1.17
  - bedtools
  - biopython
  - bwa
  - emboss
  - fastqc
  - iqtree
  - multiqc
  - pandas
  - qualimap
  - samtools = 1.17
  - snakemake-minimal
  - snp-sites
  - fastp
  - lighter
  - flash
  - unicycler
  - prokka
  - quast
  - abricate
  - gubbins
  - kmc
