$schema: "http://json-schema.org/draft-07/schema#"

description: Snakemake configuration file for Illumina pipeline
type: object

properties:
  run_type:
    description: "Indicates the type of run being conducted"
    const: "Illumina"
  reference:
    description: "Location of reference sequence. Must be in fasta format (.fasta|.fa)."
    type: string
    pattern: "^.*\\.(fasta|fa)$"
  recombinant_mask:
    description: "Published list of recombinant sites to mask from consensus sequence. Must be a '.gff' file."
    type: string
    pattern: "^$|^.*\\.gff$"
  background_dataset:
    description: "Genomes to include in the phylogenetic analysis. Must be in fasta format (.fasta|.fa)."
    type: string
    default: "<background-dataset-path>"

  preprocessing:
    description: "Metaparameters for processing of input files prior to begining of pipeline"
    type: object
    properties:
      check_size:
        description: "Whether to remove samples if there fastqs are not a required size. Empty files can disrupt the pipeline."
        type: boolean
        default: True
      minimum_size:
        description: "Minimum size in bytes an input fastq file must be to pass size filter."
        type: integer
        default: 100
    required:
      - check_size
      - minimum_size

  alignment_bwa:
    description: "Parameters for the alignment step using BWA."
    type: object
    properties:
      bwa_params:
        description: "Optional parameters passed directly to the bwa program."
        type: string
        default: "-M"
    required:
      - bwa_params
  
  coverage_mask:
    description: "Parameters required for creation of a bed depth file."
    type: object
    properties:
      required_depth:
        description: "Minimum depth for a position to not be masked."
        type: integer
        minimum: 0
        default: 15
    required:
      - required_depth

  plot_coverage:
    description: "Parameters required for creating a coverage plot."
    type: object
    properties:
      bin_size:
        description: "Size of bin in basepairs used to calculate coverage across genome."
        type: integer
        minimum: 0
        default: 10000
    required:
      - bin_size

  call_variants:
    description: "Parameters required for calling variants from an alignment."
    type: object
    properties:
      maximum_depth:
        description: "Maximum number of reads read at a position."
        type: integer
        exclusiveMinimum: 0
        default: 2000
      minimum_mapping_quality:
        description: "Minimum mapping quality for an alignment to be used."
        type: integer
        minimum: 0
        exclusiveMaximum: 255
        default: 30
      minimum_base_quality:
        description: "Minimum base quality for a base to be considered."
        type: integer
        exclusiveMinimum: 0
        maximum: 60
        default: 20
      mpileup_parameters:
        description: "Parameters passed to the 'bcftools mpileup' command."
        type: string
        default: "-B -a INFO/AD,INFO/ADF,INFO/ADR -Ou"
      call_parameters:
        description: "Paramteres passed to the 'bcftools call' command."
        type: string
        default: "-mv -Ov --ploidy 1"
    required:
      - maximum_depth
      - minimum_mapping_quality
      - minimum_base_quality
      - mpileup_parameters
      - call_parameters

  filter_variants:
    description: "Parameters involved in filtering variants prior to consensus calling."
    type: object
    properties:
      minimum_depth:
        description: "Minimum allelic depth at a position."
        type: integer
        minimum: 0
        default: 15
      minimum_strand_depth:
        description: "Minimum allelic depth on either strand."
        type: integer
        minimum: 0
        default: 5
      minimum_support:
        description: "Minimum number of reads allele must be present in."
        type: number
        exclusiveMinimum: 0
        maximum: 1
        default: 0.5
    required:
      - minimum_depth
      - minimum_strand_depth
      - minimum_support

  call_consensus:
    description: "Parameters passes to the consensus calling step"
    type: object
    properties:
      consensus_parameters:
        description: "Parameters passed to the 'bcftools consensus' program."
        type: string
        default: "--mark-del N"
    required:
      - consensus_parameters

  ########## DE NOVO ASSEMBLY ##########

  quality_trimming:
    description: "Parameters required for quality trimming of reads. using Trimmomatic."
    type: object
    properties:
      window_size:
        description: "When using a sliding window, the length of the window to average quality across."
        type: integer
        exclusiveMinimum: 0
        default: 10
      minimum_quality:
        description: "Windows with an average quality less than this will have the left-most base trimmed."
        type: integer
        exclusiveMinimum: 0
        maximum: 60
        default: 20
      minimum_length:
        description: "Minimum length of reads to be retained after trimming"
        type: integer
        exclusiveMinimum: 0
        maximum: 150
        default: 75
    required:
      - window_size
      - minimum_quality
      - minimum_length

  adapter_trimming:
    description: "Parameters required for adapter trimming of reads using bbduk.sh"
    type: object
    properties:
      firstpass_reference:
        description: "Reference to use during the first pass of trimming."
        type: string
        enum:
          - "adapters"
          - "artifacts"
          - "phix"
          - "lambda"
          - "pjet"
          - "mtst"
          - "kapa"
        default: "adapters"
      firstpass_arguments:
        description: "Arguments passed to bbduk during the first pass of trimming."
        type: string
        default: "ktrim=r k=23 mink=11 hdist=1 tpe tbo"
      secondpass_reference:
        description: "Reference used during the second pass of trimming."
        type: string
        enum:
          - "adapters"
          - "artifacts"
          - "phix"
          - "lambda"
          - "pjet"
          - "mtst"
          - "kapa"
        default: "phix"
      secondpass_arguments:
        description: "Arguments passed to bbduk during the second pass of trimming."
        type: string
        default: "k=31 hdist=1"
    required:
      - firstpass_reference
      - firstpass_arguments
      - secondpass_reference
      - secondpass_arguments

  assembly:
    description: "Parameters passed to shovill for de novo assembly."
    type: object
    properties:
      assembler:
        description: "Assembler to use"
        type: string
        enum:
          - "spades"
          - "velvet"
          - "skesa"
          - "megahit"
        default: "spades"
      assembler_arguments:
        description: "Optional arguments to pass to assembler."
        type: string
        default: ""
      minimum_contig_length:
        description: "Minimum length of contig for it to be included in output."
        type: integer
        exclusiveMinimum: 0
        default: 200
      trim:
        description: "Whether to perform optional read trimming by shovill."
        type: boolean
        default: False
      correction:
        description: "Whether to disable correction of minor assembly errors."
        type: boolean
        default: False
      read_correction:
        description: "Whether to disable correction of sequencing errors"
        type: boolean
        default: False
      read_stitching:
        description: "Whether to disable stitching of reads prior to assembly"
        type: boolean
        default: False
    required:
      - assembler
      - assembler_arguments
      - minimum_contig_length
      - trim
      - correction
      - read_correction
      - read_stitching

  contig_assignment:
    description: "Parameters passed to Prokka for performing assignment of contigs."
    type: object
    properties:
      prokka_arguments:
        description: "Arguments passed directly to Prokka."
        type: string
        default: ""
    required:
      - prokka_arguments


  tree_building:
    description: "Parameters for building a phylogeny."
    type: object
    properties:
      minimum_completeness:
        description: "Proportion of genome that must be covered in consensus for sequence to be included in phylogeny."
        type: number
        minimum: 0
        maximum: 1
        default: 0.75
      outgroup:
        description: "The taxa to use as the root during phylogenetic inference."
        type: string
      model:
        description: "Substitution model to use during phylogenetic inference."
        type: string
        default: "GTR"
      iqtree_parameters:
        description: "Parameters passed directly to iqtree."
        type: string
        default: "-bb 1000"
    required:
      - minimum_completeness
      - outgroup
      - model
      - iqtree_parameters

  antibiotic_resistance:
    description: "Parameters for assessing antibiotic resistance"
    type: object
    properties:
      database:
        description: "Antibiotic resistance database to use. Must be one recognized by abricate"
        type: string
        enum:
          - "card"
          - "ecoli_vf"
          - "plasmidfinder"
          - "ecoh"
          - "ncbi"
          - "resfinder"
          - "vfdb"
          - "megares"
          - "argannot"
        default: "card"
    required:
      - database

required:
  - run_type
  - reference
  - background_dataset
  - preprocessing
  - alignment_bwa
  - quality_trimming
  - adapter_trimming
  - assembly
  - contig_assignment
  - coverage_mask
  - plot_coverage
  - call_variants
  - filter_variants
  - call_consensus
  - recombinant_mask
  - tree_building
  - antibiotic_resistance
